[package]
name = "eth"
version = "0.1.0"
authors = ["code0xff <ian.jungyong.um@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4.3"
rust-crypto-wasm = "0.3.1"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
